export default {
  appLogo: require('./image/appLogo.png'),
  daterBackGround: require('./image/daterBackGround.png'),
  locationMap: require('./image/locationMap.png'),
  location: require('./image/location.png'),
  imageOne: require('./image/imageOne.png'),
  imageTwo: require('./image/imageTwo.png'),
  imageThird: require('./image/imageThird.png'),
  appLogoOne: require('./image/appLogoOne.png'),
  restaurantOne: require('./image/restaurantOne.png'),
  emptyEvent: require('./image/emptyEvent.png'),
  notification: require('./image/notification.png'),
  backArrow: require('./image/backArrow.png'),
  noticeBanner: require('./image/noticeBanner.png'),
  noticeBannerTwo: require('./image/noticeBannerTwo.png'),
  noticeBordEmty: require('./image/noticeBordEmty.png'),
  calender: require('./image/calender.png'),
  createPostIcon: require('./image/createPost.png'),
  backIcon: require('./image/arrow.png'),
  searchIcon: require('./image/search.png'),
  unchecked: require('./image/unchecked.png'),
  checked: require('./image/checkbox.png'),
  radioUnchecked: require('./image/radioUnchecked.png'),
  radioChecked: require('./image/radioChecked.png'),
};
